package com.dialogflow.dialogflowforbrowser.modelforgoogleactions;

public enum ErrorType {

	ERROR_TYPE_UNSPECIFIED, NOT_FOUND, INVALID, AVAILABILITY_CHANGED, PRICE_CHANGED, INCORRECT_PRICE, REQUIREMENTS_NOT_MET, TOO_LATE, NO_CAPACITY, NO_COURIER_AVAILABLE, INELIGIBLE, OUT_OF_SERVICE_AREA, CLOSED, PROMO_NOT_APPLICABLE, PROMO_NOT_RECOGNIZED, PROMO_EXPIRED, PROMO_USER_INELIGIBLE, PROMO_ORDER_INELIGIBLE, UNAVAILABLE_SLOT, FAILED_PRECONDITION, PAYMENT_DECLINED, MERCHANT_UNREACHABLE, ACCOUNT_LINKING_FAILED
}
