package com.dialogflow.dialogflowforbrowser.modelsforapi;

public enum AudioEncoding {

	AUDIO_ENCODING_UNSPECIFIED, 
	AUDIO_ENCODING_LINEAR_16, 
	AUDIO_ENCODING_FLAC, 
	AUDIO_ENCODING_MULAW, 
	AUDIO_ENCODING_AMR, 
	AUDIO_ENCODING_AMR_WB, 
	AUDIO_ENCODING_OGG_OPUS, 
	AUDIO_ENCODING_SPEEX_WITH_HEADER_BYTE
}
